#!/usr/bin/env bash

screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 0 -dataset PROTEINS"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 0 -dataset MUTAG"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 0 -dataset NCI1"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 0 -dataset CSL"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 1 -dataset TRI"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 1 -dataset TRIX"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 1 -dataset EXP"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization None -cuda 1 -dataset CEXP"

screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 2 -dataset PROTEINS"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 2 -dataset MUTAG"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 2 -dataset NCI1"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 2 -dataset CSL"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 3 -dataset TRI"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 3 -dataset TRIX"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 3 -dataset EXP"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization RNI -cuda 3 -dataset CEXP"

screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 4 -dataset PROTEINS"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 4 -dataset MUTAG"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 4 -dataset NCI1"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 4 -dataset CSL"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 5 -dataset TRI"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 5 -dataset TRIX"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 5 -dataset EXP"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization ORNI -cuda 5 -dataset CEXP"

screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 6 -dataset PROTEINS"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 6 -dataset MUTAG"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 6 -dataset NCI1"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 6 -dataset CSL"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 7 -dataset TRI"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 7 -dataset TRIX"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 7 -dataset EXP"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization IRNI -cuda 7 -dataset CEXP"

screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 8 -dataset PROTEINS"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 8 -dataset MUTAG"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 8 -dataset NCI1"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 8 -dataset CSL"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 8 -dataset TRI"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 7 -dataset TRIX"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 6 -dataset EXP"
screen -dm bash -c "source venv/bin/activate;python main.py -node_initialization CLIP -cuda 5 -dataset CEXP"
